Repository Simba-Avionic/srp, pull requests merged in 2024-06, with the labels that each got.

#104 Makr merge temp tests
  apps/ServoService/servoService.cpp
  mw/temp/controller/temp_controller.cpp
  mw/temp/subscribe_msg/subscribe_header.cpp
  mw/temp/subscribe_msg/subscribe_header.h
  mw/temp/subscribe_msg/subscribe_msg_factory.cpp
  mw/temp/subscribe_msg/subscribe_msg_factory.h
  mw/temp/tests/BUILD
  mw/temp/tests/test_subscribe_msg.cpp
  mw/temp/tests/test_subscribe_msg_factory.cpp
  mw/temp/tests/test_temp_reading_msg_factory.cpp
Labels: check_bbb

#107 mima UT temp controller
  communication-core/sockets/mock/mockSocket.h
  mw/temp/controller/BUILD
  mw/temp/controller/temp_controller.cpp
  mw/temp/controller/temp_controller.h
  mw/temp/tests/BUILD
  mw/temp/tests/test_temp_controller.cc
Labels: wontfix, check_bbb

#110 fix Calculations
  mw/i2c_service/controller/adcsensor/controller.cpp
  mw/i2c_service/controller/adcsensor/controller.hpp
Labels: check_bbb

#113 added dont merge lable
  .github/workflows/dont_merge.yaml
Labels: Dont merge
